# Generated by Django 5.2.1 on 2026-05-26 16:47

import cloudinary.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(default=None, max_length=100, unique=True)),
                ('firebase_uid', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('role', models.CharField(default='Buyer', max_length=6)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=10)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Mpesa', 'Mpesa')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='acceptor_name', to='api.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='initiator_chat', to='api.user'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.CharField(db_index=True, max_length=100)),
                ('model', models.CharField(db_index=True, max_length=100)),
                ('year', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)])),
                ('fuel_type', models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Plug-in Hybrid', 'Plug-in Hybrid')], db_index=True, max_length=100)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT')], db_index=True, max_length=100)),
                ('body_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Hatchback', 'Hatchback'), ('Wagon', 'Wagon'), ('Van', 'Van'), ('Minivan', 'Minivan')], db_index=True, max_length=100)),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount (optional)', max_digits=10, null=True)),
                ('description', models.TextField()),
                ('mileage', models.IntegerField(blank=True, db_index=True, help_text='Mileage in kilometers', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used'), ('Certified Pre-Owned', 'Certified Pre-Owned')], db_index=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(db_index=True, default='Nairobi, Kenya', max_length=100)),
                ('features', models.JSONField(blank=True, default=list, help_text="List of vehicle features (e.g., ['Sunroof', 'Leather Seats'])")),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured vehicles appear first in listings')),
                ('is_sold', models.BooleanField(db_index=True, default=False, help_text='Mark as sold to hide from main listings')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Active listings are visible to users')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this listing has been viewed')),
                ('save_count', models.IntegerField(default=0, help_text='Number of times this listing has been saved/favorited')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.user')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouritedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='api.user')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='vehicle',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='api.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image')),
                ('public_id', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 is first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Image',
                'verbose_name_plural': 'Vehicle Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model'], name='api_vehicle_make_4e33f6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price', '-created_at'], name='api_vehicle_price_708805_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['year', '-created_at'], name='api_vehicle_year_90a94e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-is_featured', '-created_at'], name='api_vehicle_is_feat_abf779_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('initiator', 'acceptor', 'vehicle')},
        ),
    ]
