# Generated by Django 5.2.1 on 2026-02-10 13:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_firebase_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-is_featured', '-created_at'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Vehicle Image', 'verbose_name_plural': 'Vehicle Images'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Active listings are visible to users'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_sold',
            field=models.BooleanField(db_index=True, default=False, help_text='Mark as sold to hide from main listings'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='save_count',
            field=models.IntegerField(default=0, help_text='Number of times this listing has been saved/favorited'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='view_count',
            field=models.IntegerField(default=0, help_text='Number of times this listing has been viewed'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order (0 is first)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Truck', 'Truck'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Hatchback', 'Hatchback'), ('Wagon', 'Wagon'), ('Van', 'Van'), ('Minivan', 'Minivan')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Used', 'Used'), ('Certified Pre-Owned', 'Certified Pre-Owned')], db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="List of vehicle features (e.g., ['Sunroof', 'Leather Seats'])"),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('Gasoline', 'Gasoline'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Plug-in Hybrid', 'Plug-in Hybrid')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured vehicles appear first in listings'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mileage',
            field=models.IntegerField(blank=True, db_index=True, help_text='Mileage in kilometers', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='region',
            field=models.CharField(db_index=True, default='Nairobi, Kenya', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('CVT', 'CVT')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='api.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model'], name='api_vehicle_make_4e33f6_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['price', '-created_at'], name='api_vehicle_price_708805_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['year', '-created_at'], name='api_vehicle_year_90a94e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-is_featured', '-created_at'], name='api_vehicle_is_feat_abf779_idx'),
        ),
    ]
