# Generated by Django 5.2.1 on 2026-02-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vehicle_options_alter_vehicleimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
