# Generated by Django 5.2.1 on 2026-02-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_chat_created_at_chat_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
